version: 2
updates:
  # For JavaScript (npm)
  - package-ecosystem: "npm"
    directory: "/" # root folder
    schedule:
      interval: "daily"

  # For Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # or "/backend" if in a subfolder
    schedule:
      interval: "daily"
